define(["require", "exports", "preact/jsx-runtime", "ojs/ojbutton"], function (require, exports, jsx_runtime_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.ProductCard = ProductCard;
    function ProductCard({ product, onAddToCart }) {
        var _a, _b, _c, _d, _e, _f;
        return ((0, jsx_runtime_1.jsxs)("article", { class: "ecom-product-card oj-sm-padding-2x oj-sm-margin-2x", children: [(0, jsx_runtime_1.jsx)("div", { class: "ecom-product-imageWrap", children: (0, jsx_runtime_1.jsx)("img", { class: "ecom-product-image", src: product.image, alt: product.title, loading: "lazy" }) }), (0, jsx_runtime_1.jsxs)("div", { class: "ecom-product-body", children: [(0, jsx_runtime_1.jsx)("div", { class: "ecom-product-title oj-typography-subheading-xs", title: product.title, children: product.title }), (0, jsx_runtime_1.jsxs)("div", { class: "ecom-product-meta oj-flex oj-sm-align-items-center oj-sm-justify-content-space-between oj-sm-margin-2x-top", children: [(0, jsx_runtime_1.jsxs)("div", { class: "ecom-product-price oj-typography-heading-xs", children: ["$", product.price.toFixed(2)] }), (0, jsx_runtime_1.jsxs)("div", { class: "ecom-product-rating oj-typography-body-xs", children: [(_d = (_c = (_b = (_a = product.rating) === null || _a === void 0 ? void 0 : _a.rate) === null || _b === void 0 ? void 0 : _b.toFixed) === null || _c === void 0 ? void 0 : _c.call(_b, 1)) !== null && _d !== void 0 ? _d : "-", " (", (_f = (_e = product.rating) === null || _e === void 0 ? void 0 : _e.count) !== null && _f !== void 0 ? _f : 0, ")"] })] }), (0, jsx_runtime_1.jsx)("div", { class: "ecom-product-category oj-typography-body-xs oj-sm-margin-2x-top", children: product.category }), (0, jsx_runtime_1.jsx)("p", { class: "ecom-product-desc oj-typography-body-sm oj-sm-margin-2x-top", title: product.description, children: product.description }), (0, jsx_runtime_1.jsx)("div", { class: "oj-sm-margin-4x-top", children: (0, jsx_runtime_1.jsx)("oj-button", { chroming: "callToAction", onojAction: () => onAddToCart(product), class: "ecom-add-btn", children: "Add to cart" }) })] })] }));
    }
});
